# Generated by Django 6.0 on 2026-02-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='Offices',
        ),
        migrations.DeleteModel(
            name='Orderdetails',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='Productlines',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
