# Generated by Django 6.0 on 2026-02-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_app', '0002_delete_customers_delete_employees_delete_offices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customernumber', models.IntegerField(db_column='customernumber', primary_key=True, serialize=False)),
                ('customername', models.CharField(db_column='customerName', max_length=50)),
                ('contactlastname', models.CharField(db_column='contactLastName', max_length=50)),
                ('contactfirstname', models.CharField(db_column='contactFirstName', max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('addressline1', models.CharField(db_column='addressLine1', max_length=50)),
                ('addressline2', models.CharField(blank=True, db_column='addressLine2', max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='postalCode', max_length=15, null=True)),
                ('country', models.CharField(max_length=50)),
                ('creditlimit', models.DecimalField(blank=True, db_column='creditLimit', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeenumber', models.IntegerField(db_column='employeeNumber', unique=True)),
                ('lastname', models.CharField(db_column='lastName', max_length=50)),
                ('firstname', models.CharField(db_column='firstName', max_length=50)),
                ('extension', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(db_column='jobTitle', max_length=50)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('officecode', models.CharField(db_column='officeCode', max_length=10, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('addressline1', models.CharField(db_column='addressLine1', max_length=50)),
                ('addressline2', models.CharField(blank=True, db_column='addressLine2', max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=50)),
                ('postalcode', models.CharField(db_column='postalCode', max_length=15)),
                ('territory', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'offices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantityordered', models.IntegerField(db_column='quantityOrdered')),
                ('priceeach', models.DecimalField(db_column='priceEach', decimal_places=2, max_digits=10)),
                ('orderlinenumber', models.SmallIntegerField(db_column='orderLineNumber')),
            ],
            options={
                'db_table': 'orderdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordernumber', models.IntegerField(db_column='orderNumber', unique=True)),
                ('orderdate', models.DateField(db_column='orderDate')),
                ('requireddate', models.DateField(db_column='requiredDate')),
                ('shippeddate', models.DateField(blank=True, db_column='shippedDate', null=True)),
                ('status', models.CharField(max_length=15)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checknumber', models.CharField(db_column='checknumber', max_length=50)),
                ('paymentdate', models.DateField(db_column='paymentDate')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productlines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productline', models.CharField(db_column='productline', max_length=50)),
                ('textdescription', models.CharField(blank=True, db_column='textDescription', max_length=4000, null=True)),
                ('htmldescription', models.TextField(blank=True, db_column='htmlDescription', null=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productlines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productcode', models.CharField(db_column='productcode', max_length=15, unique=True)),
                ('productname', models.CharField(db_column='productName', max_length=70)),
                ('productscale', models.CharField(db_column='productScale', max_length=10)),
                ('productvendor', models.CharField(db_column='productVendor', max_length=50)),
                ('productdescription', models.TextField(db_column='productDescription')),
                ('quantityinstock', models.SmallIntegerField(db_column='quantityInStock')),
                ('buyprice', models.DecimalField(db_column='buyPrice', decimal_places=2, max_digits=10)),
                ('msrp', models.DecimalField(db_column='MSRP', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
